#define ESC	27
#define ENTER	13

#define LEFT	75
#define	RIGHT	77
#define UP	72
#define	DOWN	80

#define HOME	71
#define	END	79
#define PGUP	73
#define	PGDN	81
#define	INS	82
#define	DEL	83

#define F1	59
#define F2	60
#define F3 	61
#define F4      62
#define F5      63
#define F6      64
#define F7      65
#define F8      66
#define F9      67
#define F10     68

#define SF1	84
#define SF2     85
#define SF3     86
#define SF4     87
#define SF5     88
#define SF6     89
#define SF7     90
#define SF8     91
#define SF9     92
#define SF10    93

#define CF1	94
#define CF2     95
#define CF3     96
#define CF4     97
#define CF5     98
#define CF6     99
#define CF7     100
#define CF8     101
#define CF9     102
#define CF10    103

#define AF1	104
#define AF2     105
#define AF3     106
#define AF4     107
#define AF5     108
#define AF6     109
#define AF7     110
#define AF8     111
#define AF9     112
#define AF10    113
